name: pre-commit check

on:
  push:
  pull_request:

jobs:
  pre-commit-local:
    uses: ./.github/workflows/pre-commit-shared.yml
    if: github.repository == 'python-social-auth/social-core'
  pre-commit:
    uses: python-social-auth/social-core/.github/workflows/pre-commit-shared.yml@master
    if: github.repository != 'python-social-auth/social-core'
